### ISSUE TITLE
Can you remove console.log messages?

### ISSUE THREAD

**Issue by ilearnio** [rudiedirkx/RWeb#57]
Hi, I enjoy using your plugin. But it's annoying that it writes messages like

```
rweb.sites ("localhost:3100"): 121.434ms
``` 

to the console everytime I reload my local site. Could you please remove or comment all `console.log` lines in your code?

Thanks

**Comment by rudiedirkx** [comment]
I like those (of course), but it could be an option. Patches very welcome.
